name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> env_vars
          echo "DB_USER=${{ secrets.DB_USER }}" >> env_vars
          echo "DB_PASSWORD=${{ secrets.Password }}" >> env_vars
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> env_vars
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> env_vars

      - name: Create webapp.zip
        run: |
          mkdir -p packer-template
          zip -r webapp.zip . -x ".git/*" "packer-template/*" ".github/*" "env_vars"
          mv webapp.zip packer-template/

      - name: Move necessary files to packer-template
        run: |
          mv my-app.service packer-template/
          mv packer/install_webapp.sh packer-template/
          mv packer/test.pkr.hcl packer-template/
          mv env_vars packer-template/

      - name: Run Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd packer-template
          packer init test.pkr.hcl
          packer build -var-file=env_vars test.pkr.hcl

      - name: Upload webapp.zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: packer-template/webapp.zip