name: Packer Status Check

on:
  pull_request:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Packer Init
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }

      - name: Run Packer Format Check
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer hashicorp/packer:latest fmt -check test.pkr.hcl


      - name: Run Packer Validate
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
