name: Build Packer Custom Image

on:
  pull_request:
    types: [closed]  # Trigger this only when a pull request is closed (merged)

jobs:
  build:
    if: github.event.pull_request.merged == true  # Ensure the PR is merged

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1

      - name: Run integration tests
        run: |
          npm install  # Install dependencies if needed
          npm test     # Run your integration tests

      - name: Build application artifact
        run: |
          # Add commands to build your application artifact, such as:
          npm install  # Install dependencies for your application
          npm run build  # Assuming this command builds your application

      - name: Build custom image with Packer
        run: packer build C:/Users/hp/Desktop/Packer/webapp/pkr.hcl  # Use the correct path to your Packer configuration file
