name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures all history is fetched

      - name: Create repository archive
        run: |
          zip -r webapp.zip . -x '*.git*'
          mkdir -p packer
          mv webapp.zip packer/

      - name: Run Packer Init
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }

      - name: Run Packer Format Check
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
          hashicorp/packer:latest fmt -check test.pkr.hcl || { echo "Packer format check failed"; exit 1; }

      - name: Run Packer Validate
        env:
          MY_APP_SERVICE_CONTENT: ${{ secrets.MY_APP_SERVICE_CONTENT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
          -e MY_APP_SERVICE_CONTENT -e DB_PASSWORD -e DB_NAME \
          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate \
          -var "my_app_service_content=${MY_APP_SERVICE_CONTENT}" \
          -var "db_password=${DB_PASSWORD}" \
          -var "db_name=${DB_NAME}" \
          test.pkr.hcl || { echo "Packer validate failed"; exit 1; }