name: Packer Status Check

on:
  pull_request:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1

      - name: Run packer fmt
        run: packer fmt -check .

      - name: Run packer validate
        run: packer validate .

