name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create webapp.zip
        run: |
          mkdir -p packer-template
          zip -r webapp.zip . -x ".git/*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/
      - name: Verify webapp.zip location
        run: |
            ls -la packer-template/webapp.zip
            file packer-template/webapp.zip
      - name: Verify webapp.zip location
        run: |
          ls -la packer-template/webapp.zip
          file packer-template/webapp.zip
          
      - name: Move necessary files to packer-template
        run: |
          mv my-app.service packer-template/
          mv packer/install_webapp.sh packer-template/
          mv packer/test.pkr.hcl packer-template/

      - name: List packer-template contents
        run: ls -la packer-template
      - name: Check necessary files
        run: |
          for file in webapp.zip my-app.service install_webapp.sh test.pkr.hcl; do
            if [ ! -f "packer-template/$file" ]; then
              echo "$file not found in packer-template directory"
              exit 1
            fi
          done

      - name: Run Packer Init
        run: |
          echo "Running Packer Init..."
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template \
            -v packer_plugins:/root/.config/packer/plugins \
            hashicorp/packer:1.11.2 init test.pkr.hcl

      - name: Run Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_PASSWORD: ${{ secrets.Password }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Running Packer Build..."
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template \
            -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e Password -e DB_NAME \
            -v packer_plugins:/root/.config/packer/plugins \
            hashicorp/packer:latest build \
            -var "Password=${DB_PASSWORD}" \
            -var "DB_NAME=${DB_NAME}" \
            test.pkr.hcl || { echo "Packer build failed"; exit 1; }

      - name: Extract AMI ID
        run: |
          AMI_ID=$(docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template \
            hashicorp/packer:latest \
            jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "Built AMI ID: $AMI_ID"
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Output AMI ID
        run: echo "Built AMI ID ${{ env.AMI_ID }}"