name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create webapp.zip
        run: |
          mkdir -p packer-template
          zip -r webapp.zip . -x ".git/*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/

      - name: List repository contents
        run: |
          echo "Root directory contents:"
          ls -la
          echo "packer-template directory contents:"
          ls -la packer-template

      - name: Check necessary files
        run: |
          for file in webapp.zip my-app.service install_webapp.sh; do
            if [ ! -f "packer-template/$file" ]; then
              echo "$file not found in packer-template directory"
              echo "Current directory structure:"
              find . -type f
              exit 1
            fi
          done

      - name: Upload webapp.zip as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifact
          path: packer-template/webapp.zip

      - name: Run Packer Init
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template -v packer_plugins:/root/.config/packer/plugins \
            hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }

      - name: Run Packer Format Check
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template hashicorp/packer:latest fmt -check test.pkr.hcl \
            || { echo "Packer format check failed"; exit 1; }

      - name: Run Packer Validate
        env:
          MY_APP_SERVICE_CONTENT: ${{ secrets.MY_APP_SERVICE_CONTENT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template -e MY_APP_SERVICE_CONTENT -e DB_PASSWORD -e DB_NAME \
            -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate \
            -var "MY_APP_SERVICE_CONTENT=${MY_APP_SERVICE_CONTENT}" \
            -var "Password=${DB_PASSWORD}" \
            -var "DB_NAME=${DB_NAME}" \
            test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
