name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create webapp.zip
        run: |
          mkdir -p packer-template
          zip -r webapp.zip . -x ".git/*" "packer-template/*" ".github/*"
          mv webapp.zip packer-template/
      - name: Move my-app.service to packer-template
        run: |
          mv my-app.service packer-template/
      - name: Move install_webapp.sh to packer-template
        run: |
          mv packer/install_webapp.sh packer-template/
      - name: Move test.pkr.hcl to packer-template
        run: |
          mv packer/test.pkr.hcl packer-template/
      - name: List repository contents
        run: |
          echo "Root directory contents:"
          ls -la
          echo "packer-template directory contents:"
          ls -la packer-template
      - name: Check necessary files
        run: |
          for file in webapp.zip my-app.service install_webapp.sh test.pkr.hcl; do
            if [ ! -f "packer-template/$file" ]; then
              echo "$file not found in packer-template directory"
              echo "Current directory structure:"
              find . -type f
              exit 1
            fi
          done
      - name: Upload webapp.zip as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifact
          path: packer-template/webapp.zip

      - name: Run Packer Init
        run: |
          echo "Running Packer Init..."
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template -v packer_plugins:/root/.config/packer/plugins \
            hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }
          echo "Packer Init completed successfully."
      - name: Run Packer Format Check
        run: |
          echo "Running Packer Format Check..."
          docker run --rm -v "${{ github.workspace }}:/workspace" \
            -w /workspace/packer-template hashicorp/packer:latest fmt -check test.pkr.hcl \
            || { echo "Packer format check failed"; exit 1; }
      - name: Packer validate
        run: |
          cd packer-template
          # packer init test.pkr.hcl
          packer validate -syntax-only test.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false

      - name: Prevent merge on failure
        if: failure()
        run: |
          echo "Packer validation failed. This pull request cannot be merged."
          exit 1