name: CI Workflow

on:
  pull_request:
    branches:
      - main  # Specify the branch for protection

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up test database
        run: npm run setup-test-db  # Ensure the test database is set up before running tests

      - name: Run tests
        run: npm test  # This runs both your Jest and integration tests
