name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.Password }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - ${{ secrets.DB_PORT }}:${{ secrets.DB_PORT }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        APP_PORT: ${{ secrets.APP_PORT }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.Password}}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: npm test

    - name: Run integration tests
      env:
        APP_PORT: ${{ secrets.APP_PORT }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.Password}}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: npm run test:integration